# Generated by Django 6.0.4 on 2026-10-04 02:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cuidados", "0001_initial"),
        ("hogares", "0001_initial"),
        ("medicamentos", "0002_nombres_y_formula_privada"),
        ("residentes", "0004_quitar_alergias_y_antecedentes_texto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionEventos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modo_reporte",
                    models.CharField(
                        choices=[
                            (
                                "identificado",
                                "Identificado: el jefe de enfermería, el médico y el administrador ven quién reportó",
                            ),
                            (
                                "confidencial",
                                "Confidencial: solo el jefe de enfermería ve quién reportó; en listados e indicadores no aparece",
                            ),
                            (
                                "anonimo",
                                "Anónimo voluntario: quien reporta puede no dejar su nombre (no se guarda en ninguna parte)",
                            ),
                        ],
                        default="confidencial",
                        max_length=15,
                        verbose_name="Quién reportó",
                    ),
                ),
                (
                    "horas_vigilancia_caida",
                    models.PositiveSmallIntegerField(
                        default=72,
                        verbose_name="Horas de vigilancia después de una caída",
                    ),
                ),
                (
                    "intervalo_vigilancia_horas",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="Revisar cada (horas)"
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hogar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_eventos",
                        to="hogares.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de eventos adversos",
                "verbose_name_plural": "Configuraciones de eventos adversos",
            },
        ),
        migrations.CreateModel(
            name="EventoAdverso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("caida", "Caída"),
                            ("medicacion", "Error de medicación"),
                            ("lpp", "Lesión por presión aparecida en el hogar"),
                            ("reaccion", "Reacción adversa a un medicamento"),
                            ("fuga", "Fuga o salida no autorizada"),
                            ("broncoaspiracion", "Atragantamiento o broncoaspiración"),
                            ("agresion", "Agresión o conflicto entre residentes"),
                            ("lesion", "Lesión, golpe o quemadura"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Cuándo pasó"
                    ),
                ),
                (
                    "lugar",
                    models.CharField(
                        choices=[
                            ("habitacion", "Habitación"),
                            ("bano", "Baño"),
                            ("comedor", "Comedor"),
                            ("pasillo", "Pasillo"),
                            ("sala", "Sala o zona común"),
                            ("exterior", "Patio o zona exterior"),
                            ("escaleras", "Escaleras"),
                            ("fuera", "Fuera del hogar"),
                            ("otro", "Otro"),
                        ],
                        default="habitacion",
                        max_length=15,
                        verbose_name="Dónde pasó",
                    ),
                ),
                (
                    "lugar_detalle",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Detalle del lugar"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Qué pasó")),
                (
                    "testigo",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Quién lo presenció o lo encontró",
                    ),
                ),
                (
                    "accion_inmediata",
                    models.TextField(verbose_name="Qué se hizo en el momento"),
                ),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("sin_dano", "Sin daño"),
                            (
                                "leve",
                                "Daño leve (no requiere más que primeros auxilios)",
                            ),
                            (
                                "moderado",
                                "Daño moderado (requiere atención médica o tratamiento)",
                            ),
                            (
                                "grave",
                                "Daño grave (hospitalización o lesión permanente)",
                            ),
                            ("muerte", "Muerte"),
                        ],
                        max_length=10,
                        verbose_name="Daño al residente",
                    ),
                ),
                (
                    "aviso_medico",
                    models.BooleanField(
                        default=False, verbose_name="Se avisó al médico"
                    ),
                ),
                (
                    "aviso_familia",
                    models.BooleanField(
                        default=False, verbose_name="Se avisó a la familia"
                    ),
                ),
                (
                    "aviso_familia_quien",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="A quién de la familia"
                    ),
                ),
                (
                    "golpe_cabeza",
                    models.BooleanField(
                        default=False, verbose_name="Se golpeó la cabeza"
                    ),
                ),
                (
                    "perdida_conciencia",
                    models.BooleanField(
                        default=False, verbose_name="Perdió el conocimiento"
                    ),
                ),
                (
                    "anticoagulantes",
                    models.BooleanField(
                        default=False, verbose_name="Toma anticoagulantes"
                    ),
                ),
                (
                    "lesiones",
                    models.TextField(blank=True, verbose_name="Lesiones encontradas"),
                ),
                (
                    "tipo_error",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("omision", "No se suministró una dosis"),
                            ("dosis", "Dosis equivocada"),
                            ("medicamento", "Medicamento equivocado"),
                            ("residente", "Residente equivocado"),
                            ("hora", "Hora equivocada"),
                            ("via", "Vía equivocada"),
                            ("vencido", "Medicamento vencido"),
                            ("otro", "Otro"),
                        ],
                        max_length=15,
                        verbose_name="Qué falló",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("manual", "Reporte del personal"),
                            ("herida", "Desde una herida"),
                            ("medicamento", "Desde una corrección de suministro"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("anonimo", models.BooleanField(default=False)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "hash_integridad",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Por analizar"),
                            ("cerrado", "Analizado y cerrado"),
                        ],
                        default="abierto",
                        max_length=10,
                    ),
                ),
                (
                    "causas",
                    models.TextField(blank=True, verbose_name="Por qué pasó (causas)"),
                ),
                (
                    "acciones_mejora",
                    models.TextField(
                        blank=True,
                        verbose_name="Qué se va a hacer para que no se repita",
                    ),
                ),
                (
                    "responsable_acciones",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Responsable de las acciones",
                    ),
                ),
                (
                    "fecha_limite_acciones",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha límite de las acciones",
                    ),
                ),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "administracion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_adversos",
                        to="medicamentos.administracion",
                    ),
                ),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "herida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_adversos",
                        to="cuidados.herida",
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_adversos",
                        to="hogares.hogar",
                    ),
                ),
                (
                    "prescripcion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_adversos",
                        to="medicamentos.prescripcion",
                        verbose_name="Orden médica",
                    ),
                ),
                (
                    "reportado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_adversos",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento adverso",
                "verbose_name_plural": "Eventos adversos",
                "ordering": ["-fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="NotaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(verbose_name="Nota")),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas",
                        to="eventos.eventoadverso",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="VigilanciaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programada", models.DateTimeField()),
                ("realizada", models.DateTimeField(blank=True, null=True)),
                (
                    "conciencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alerta", "Alerta y orientado, como siempre"),
                            ("somnoliento", "Más somnoliento de lo usual"),
                            ("confuso", "Confuso o desorientado"),
                            ("no_responde", "No responde o cuesta despertarlo"),
                        ],
                        max_length=15,
                        verbose_name="Estado de conciencia",
                    ),
                ),
                (
                    "dolor",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Dolor (0 a 10)"
                    ),
                ),
                (
                    "hallazgos",
                    models.TextField(
                        blank=True,
                        verbose_name="Hallazgos (signos, hematomas, cómo camina)",
                    ),
                ),
                (
                    "requiere_medico",
                    models.BooleanField(
                        default=False, verbose_name="Necesita valoración médica"
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vigilancias",
                        to="eventos.eventoadverso",
                    ),
                ),
                (
                    "realizada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["programada"],
            },
        ),
        migrations.AddIndex(
            model_name="eventoadverso",
            index=models.Index(
                fields=["hogar", "fecha_hora"], name="eventos_eve_hogar_i_b5abdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventoadverso",
            index=models.Index(
                fields=["residente", "fecha_hora"],
                name="eventos_eve_residen_f5db43_idx",
            ),
        ),
    ]
