# Generated by Django 6.0.4 on 2026-04-30 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('inicio_sesion', 'Inicio de sesión'), ('cierre_sesion', 'Cierre de sesión'), ('consulta_expediente', 'Consulta de expediente'), ('creacion_nota', 'Creación de nota clínica'), ('exportacion', 'Exportación de expediente'), ('creacion_residente', 'Registro de residente'), ('asignacion_cama', 'Asignación de cama')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
