# Generated by Django 5.2.17 on 2026-09-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0002_alter_registroauditoria_accion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("inicio_sesion", "Inicio de sesión"),
                    ("cierre_sesion", "Cierre de sesión"),
                    ("consulta_expediente", "Consulta de expediente"),
                    ("creacion_nota", "Creación de nota clínica"),
                    ("exportacion", "Exportación de expediente"),
                    ("creacion_residente", "Registro de residente"),
                    ("asignacion_cama", "Asignación de cama"),
                    ("reseteo_password", "Restablecimiento de contraseña"),
                    ("prescripcion_creada", "Registro de tratamiento formulado"),
                    ("prescripcion_suspendida", "Suspensión de tratamiento"),
                    ("ingreso_medicamento", "Ingreso de medicamento"),
                    ("no_administracion", "No administración de medicamento"),
                    ("ajuste_inventario", "Ajuste de inventario de medicamentos"),
                    ("descarte_vencido", "Descarte de lote vencido"),
                    ("anulacion_administracion", "Anulación de administración"),
                    ("uso_botiquin", "Uso del botiquín del hogar"),
                ],
                max_length=50,
            ),
        ),
    ]
