# Generated by Django 6.0.4 on 2026-10-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0003_alter_registroauditoria_accion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("inicio_sesion", "Inicio de sesión"),
                    ("cierre_sesion", "Cierre de sesión"),
                    ("consulta_expediente", "Consulta de expediente"),
                    ("creacion_nota", "Creación de nota clínica"),
                    ("exportacion", "Exportación de expediente"),
                    ("creacion_residente", "Registro de residente"),
                    ("asignacion_cama", "Asignación de cama"),
                    ("reseteo_password", "Restablecimiento de contraseña"),
                    ("prescripcion_creada", "Registro de orden médica"),
                    ("prescripcion_suspendida", "Suspensión de orden médica"),
                    (
                        "ingreso_medicamento",
                        "Medicamentos guardados en el cajón o el botiquín",
                    ),
                    ("no_administracion", "Medicamento no suministrado"),
                    ("ajuste_inventario", "Ajuste de inventario de medicamentos"),
                    ("descarte_vencido", "Descarte de lote vencido"),
                    ("anulacion_administracion", "Anulación de un suministro"),
                    ("uso_botiquin", "Uso del botiquín del hogar"),
                    ("examen_registrado", "Registro de orden de examen"),
                    ("resultado_examen", "Carga de resultado de examen"),
                    ("adenda_examen", "Información adicional en examen"),
                    ("correccion_resultado", "Corrección de valor de examen"),
                    ("revision_examen", "Revisión médica de examen"),
                    ("cancelacion_examen", "Cancelación de orden de examen"),
                    ("consulta_resultado", "Consulta de archivo de resultado"),
                ],
                max_length=50,
            ),
        ),
    ]
