# Generated by Django 6.0.4 on 2026-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0012_acciones_cuidados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("inicio_sesion", "Inicio de sesión"),
                    ("cierre_sesion", "Cierre de sesión"),
                    ("consulta_expediente", "Consulta de expediente"),
                    ("creacion_nota", "Creación de nota clínica"),
                    ("exportacion", "Exportación de expediente"),
                    ("creacion_residente", "Registro de residente"),
                    ("asignacion_cama", "Asignación de cama"),
                    ("reseteo_password", "Restablecimiento de contraseña"),
                    ("prescripcion_creada", "Registro de orden médica"),
                    ("prescripcion_suspendida", "Suspensión de orden médica"),
                    (
                        "ingreso_medicamento",
                        "Medicamentos guardados en el cajón o el botiquín",
                    ),
                    ("no_administracion", "Medicamento no suministrado"),
                    ("ajuste_inventario", "Ajuste de inventario de medicamentos"),
                    ("descarte_vencido", "Descarte de lote vencido"),
                    ("anulacion_administracion", "Anulación de un suministro"),
                    ("uso_botiquin", "Uso del botiquín"),
                    ("examen_registrado", "Registro de orden de examen"),
                    ("resultado_examen", "Carga de resultado de examen"),
                    ("adenda_examen", "Información adicional en examen"),
                    ("correccion_resultado", "Corrección de valor de examen"),
                    ("revision_examen", "Revisión médica de examen"),
                    ("cancelacion_examen", "Cancelación de orden de examen"),
                    ("consulta_resultado", "Consulta de archivo de resultado"),
                    ("alergia_registrada", "Registro de alergia"),
                    ("alergia_inactivada", "Inactivación de alergia"),
                    ("sin_alergias", "Declaración de sin alergias conocidas"),
                    ("antecedente_registrado", "Registro de antecedente"),
                    ("antecedente_inactivado", "Inactivación de antecedente"),
                    ("orden_pese_a_alergia", "Orden médica registrada pese a alergia"),
                    ("cita_registrada", "Cita médica agendada"),
                    ("cita_modificada", "Cita médica corregida o reprogramada"),
                    ("cita_cerrada", "Registro de lo que pasó en una cita"),
                    ("cita_cancelada", "Cita médica cancelada"),
                    ("aviso_creado", "Aviso manual publicado"),
                    ("alerta_atendida", "Alerta atendida"),
                    ("alerta_descartada", "Alerta descartada"),
                    ("configuracion_alertas", "Cambio en la configuración de alertas"),
                    ("signos_registrados", "Registro de signos vitales"),
                    ("liquidos_registrados", "Registro de líquidos"),
                    ("signos_anulados", "Anulación de signos vitales o líquidos"),
                    ("rango_signos", "Cambio de rangos de signos vitales"),
                    (
                        "valoracion_registrada",
                        "Aplicación de escala de valoración geriátrica",
                    ),
                    (
                        "valoracion_anulada",
                        "Anulación de escala de valoración geriátrica",
                    ),
                    (
                        "configuracion_valoracion",
                        "Cambio de escalas exigidas y periodicidad",
                    ),
                    (
                        "plan_atencion",
                        "Plan de atención (creación, activación u objetivo nuevo)",
                    ),
                    (
                        "devolucion_medicamentos",
                        "Devolución de medicamentos a la familia",
                    ),
                    (
                        "configuracion_medicamentos",
                        "Cambio en la configuración de medicamentos",
                    ),
                    ("plan_cuidados", "Cambio del plan de cuidados de un residente"),
                    (
                        "cuidado_anulado",
                        "Anulación de un cuidado o de un seguimiento de herida",
                    ),
                    ("herida_registrada", "Registro de herida o lesión por presión"),
                    ("herida_seguimiento", "Seguimiento o curación de herida"),
                    ("herida_cerrada", "Cierre de herida"),
                    ("consulta_foto_herida", "Consulta de foto de herida"),
                    ("dieta_indicada", "Dieta indicada o cambiada"),
                    (
                        "tipo_dieta_creado",
                        "Tipo de dieta agregado al catálogo del hogar",
                    ),
                    ("ingesta_corregida", "Corrección de un registro de ingesta"),
                    (
                        "configuracion_nutricion",
                        "Cambio de comidas y metas de líquidos del hogar",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
