# Generated by Django 5.2.17 on 2026-09-17 03:10

import django.db.models.deletion
import django.utils.timezone
import medicamentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hogares", "0001_initial"),
        ("notas_clinicas", "0002_notaclinica_deposicion_notaclinica_diuresis_and_more"),
        ("residentes", "0003_remove_expedienteingreso_diagnosticos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HorarioPrescripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora", models.TimeField()),
            ],
            options={
                "verbose_name": "Horario de prescripción",
                "verbose_name_plural": "Horarios de prescripción",
                "db_table": "medicamentos_horario_prescripcion",
                "ordering": ["hora"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionMedicamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dias_semaforo_verde",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Días para semáforo verde"
                    ),
                ),
                (
                    "dias_semaforo_amarillo",
                    models.PositiveIntegerField(
                        default=180, verbose_name="Días para semáforo amarillo"
                    ),
                ),
                (
                    "horas_estandar",
                    models.JSONField(
                        default=medicamentos.models.ConfiguracionMedicamentos._horas_estandar_default,
                        verbose_name="Horas estándar sugeridas",
                    ),
                ),
                (
                    "ventana_ronda_horas",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Ventana de la ronda (horas)"
                    ),
                ),
                (
                    "minutos_anulacion",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Minutos para anulación"
                    ),
                ),
                (
                    "alerta_stock_dias",
                    models.PositiveIntegerField(
                        default=5,
                        verbose_name="Avisar cuando queden menos de N días de tratamiento",
                    ),
                ),
                (
                    "hogar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_medicamentos",
                        to="hogares.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de medicamentos",
                "verbose_name_plural": "Configuraciones de medicamentos",
                "db_table": "medicamentos_configuracion",
            },
        ),
        migrations.CreateModel(
            name="IngresoMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lote", models.CharField(max_length=50, verbose_name="Lote")),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="Fecha de vencimiento"),
                ),
                (
                    "cantidad_ingresada",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Cantidad ingresada",
                    ),
                ),
                (
                    "cantidad_disponible",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Cantidad disponible",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("tabletas", "Tabletas"),
                            ("capsulas", "Cápsulas"),
                            ("ml", "mL"),
                            ("ampollas", "Ampollas"),
                            ("sobres", "Sobres"),
                            ("frascos", "Frascos"),
                            ("otro", "Otro"),
                        ],
                        default="tabletas",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Fecha de ingreso",
                    ),
                ),
                (
                    "entregado_por",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del familiar que lo trajo (vacío si es compra del hogar)",
                        max_length=200,
                        verbose_name="Entregado por",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("agotado", "Agotado"),
                            ("vencido", "Vencido"),
                            ("descartado", "Descartado"),
                            ("devuelto", "Devuelto a la familia"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="botiquin_ingresos",
                        to="hogares.hogar",
                        verbose_name="Hogar (botiquín común)",
                    ),
                ),
                (
                    "recibido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingresos_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingresos_medicamento",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso de medicamento",
                "verbose_name_plural": "Ingresos de medicamento",
                "db_table": "medicamentos_ingreso",
                "ordering": ["fecha_vencimiento"],
            },
        ),
        migrations.CreateModel(
            name="Administracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(
                        blank=True,
                        help_text="Vacío en tomas PRN",
                        null=True,
                        verbose_name="Fecha y hora programada",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("administrado", "Administrado"),
                            ("no_administrado", "No administrado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_administracion", models.DateTimeField(auto_now_add=True)),
                (
                    "cantidad_administrada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Cantidad administrada",
                    ),
                ),
                (
                    "motivo_no_administracion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sin_existencias", "Sin existencias"),
                            (
                                "residente_rechazo",
                                "El residente rechazó el medicamento",
                            ),
                            ("suspendido_por_medico", "Suspendido por el médico"),
                            ("residente_hospitalizado", "Residente hospitalizado"),
                            ("residente_ausente", "Residente ausente"),
                            ("residente_dormido", "Residente dormido"),
                            (
                                "contraindicado_en_el_momento",
                                "Contraindicado en el momento",
                            ),
                            ("lote_vencido", "Lote vencido"),
                            ("otro", "Otro"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "observacion",
                    models.TextField(
                        blank=True,
                        help_text="Obligatoria si la dosis fue parcial, si es PRN, o si se usó el botiquín",
                    ),
                ),
                (
                    "motivo_uso_botiquin",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "prestamo",
                                "Préstamo — se espera reposición de la familia",
                            ),
                            ("emergencia", "Emergencia — no se espera reposición"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "repuesto",
                    models.BooleanField(
                        default=False,
                        help_text="Solo aplica si motivo_uso_botiquin = préstamo",
                        verbose_name="Repuesto",
                    ),
                ),
                ("fecha_reposicion", models.DateField(blank=True, null=True)),
                ("anulada", models.BooleanField(default=False)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "hash_integridad",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "administrada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administraciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "anulada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anulaciones_administracion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nota_clinica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administraciones_medicamento",
                        to="notas_clinicas.notaclinica",
                    ),
                ),
                (
                    "repuesto_marcado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reposiciones_marcadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administraciones_medicamento",
                        to="residentes.residente",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administraciones",
                        to="medicamentos.horarioprescripcion",
                    ),
                ),
                (
                    "ingreso_usado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administraciones",
                        to="medicamentos.ingresomedicamento",
                        verbose_name="Lote usado (FEFO)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administración",
                "verbose_name_plural": "Administraciones",
                "db_table": "medicamentos_administracion",
                "ordering": ["-fecha_administracion"],
            },
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_generico",
                    models.CharField(max_length=200, verbose_name="Nombre genérico"),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre comercial"
                    ),
                ),
                (
                    "concentracion",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Concentración"
                    ),
                ),
                (
                    "forma_farmaceutica",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tableta", "Tableta"),
                            ("capsula", "Cápsula"),
                            ("jarabe", "Jarabe"),
                            ("suspension", "Suspensión"),
                            ("gotas", "Gotas"),
                            ("ampolla", "Ampolla"),
                            ("crema_ungüento", "Crema / Ungüento"),
                            ("parche", "Parche"),
                            ("inhalador", "Inhalador"),
                            ("supositorio", "Supositorio"),
                            ("ovulo", "Óvulo"),
                            ("insulina", "Insulina"),
                        ],
                        max_length=30,
                        verbose_name="Forma farmacéutica",
                    ),
                ),
                (
                    "unidad_dosificacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tableta", "Tableta"),
                            ("capsula", "Cápsula"),
                            ("ml", "mL"),
                            ("gota", "Gota"),
                            ("mg", "mg"),
                            ("aplicacion", "Aplicación"),
                            ("puff", "Puff"),
                            ("ui", "UI"),
                            ("sobre", "Sobre"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Unidad de dosificación",
                    ),
                ),
                (
                    "requiere_refrigeracion",
                    models.BooleanField(
                        default=False, verbose_name="Requiere refrigeración"
                    ),
                ),
                (
                    "control_especial",
                    models.BooleanField(
                        default=False, verbose_name="Medicamento de control especial"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicamentos",
                        to="hogares.hogar",
                        verbose_name="Hogar (vacío = catálogo general)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
                "db_table": "medicamentos_medicamento",
                "ordering": ["nombre_generico", "concentracion"],
            },
        ),
        migrations.AddField(
            model_name="ingresomedicamento",
            name="medicamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingresos",
                to="medicamentos.medicamento",
            ),
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida_administracion", "Salida por administración"),
                            ("ajuste", "Ajuste"),
                            ("descarte_vencido", "Descarte por vencimiento"),
                            ("devolucion_familia", "Devolución a la familia"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positiva en entradas, negativa en salidas",
                        max_digits=8,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True, help_text="Obligatorio en ajuste y descarte"
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "administracion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos",
                        to="medicamentos.administracion",
                    ),
                ),
                (
                    "ingreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="medicamentos.ingresomedicamento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_inventario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
                "db_table": "medicamentos_movimiento_inventario",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Prescripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosis_cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Cantidad de la dosis",
                    ),
                ),
                (
                    "dosis_unidad",
                    models.CharField(
                        choices=[
                            ("tableta", "Tableta"),
                            ("capsula", "Cápsula"),
                            ("ml", "mL"),
                            ("gota", "Gota"),
                            ("mg", "mg"),
                            ("aplicacion", "Aplicación"),
                            ("puff", "Puff"),
                            ("ui", "UI"),
                            ("sobre", "Sobre"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Unidad de la dosis",
                    ),
                ),
                (
                    "via_administracion",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("sublingual", "Sublingual"),
                            ("topica", "Tópica"),
                            ("oftalmica", "Oftálmica"),
                            ("otica", "Ótica"),
                            ("nasal", "Nasal"),
                            ("inhalada", "Inhalada"),
                            ("subcutanea", "Subcutánea"),
                            ("intramuscular", "Intramuscular"),
                            ("intravenosa", "Intravenosa"),
                            ("rectal", "Rectal"),
                            ("vaginal", "Vaginal"),
                            ("transdermica", "Transdérmica"),
                        ],
                        default="oral",
                        max_length=20,
                        verbose_name="Vía de administración",
                    ),
                ),
                (
                    "tipo_pauta",
                    models.CharField(
                        choices=[
                            ("horarios_fijos", "Horarios fijos"),
                            ("prn", "Por razón necesaria (PRN)"),
                        ],
                        default="horarios_fijos",
                        max_length=20,
                        verbose_name="Tipo de pauta",
                    ),
                ),
                (
                    "frecuencia_minima_horas",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Solo aplica a pautas PRN.",
                        null=True,
                        verbose_name="Frecuencia mínima entre tomas (horas)",
                    ),
                ),
                (
                    "dosis_maxima_dia",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tope informativo, solo aplica a pautas PRN.",
                        null=True,
                        verbose_name="Máximo de tomas al día",
                    ),
                ),
                (
                    "dias_semana",
                    models.CharField(
                        default="LMXJVSD",
                        help_text='L=lunes ... D=domingo, ej: "LMXJVSD" o "LXV"',
                        max_length=7,
                        verbose_name="Días de la semana",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Vacío = tratamiento crónico / indefinido",
                        null=True,
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "cantidad_total_formulada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Informativo, ej: 21 tabletas",
                        max_digits=8,
                        null=True,
                        verbose_name="Cantidad total formulada",
                    ),
                ),
                (
                    "indicaciones",
                    models.TextField(
                        blank=True,
                        help_text="Ej: con alimentos, no triturar, media hora antes",
                        verbose_name="Indicaciones",
                    ),
                ),
                (
                    "formulada_por",
                    models.CharField(
                        help_text='Ej: "Dr. Restrepo — Sanitas"',
                        max_length=200,
                        verbose_name="Formulada por",
                    ),
                ),
                ("fecha_formula", models.DateField(verbose_name="Fecha de la fórmula")),
                (
                    "numero_formula",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de fórmula"
                    ),
                ),
                (
                    "archivo_formula",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="medicamentos/formulas/%Y/%m/",
                        verbose_name="Archivo de la fórmula (foto o escaneo)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("suspendida", "Suspendida"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="activa",
                        max_length=20,
                    ),
                ),
                (
                    "motivo_suspension",
                    models.TextField(blank=True, verbose_name="Motivo de suspensión"),
                ),
                ("fecha_suspension", models.DateTimeField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "diagnostico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescripciones",
                        to="residentes.diagnosticoresidente",
                        verbose_name="Diagnóstico relacionado",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescripciones",
                        to="medicamentos.medicamento",
                    ),
                ),
                (
                    "reemplaza_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reemplazos",
                        to="medicamentos.prescripcion",
                        verbose_name="Reemplaza a",
                    ),
                ),
                (
                    "registrada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescripciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescripciones",
                        to="residentes.residente",
                    ),
                ),
                (
                    "suspendida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescripciones_suspendidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescripción",
                "verbose_name_plural": "Prescripciones",
                "db_table": "medicamentos_prescripcion",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.AddField(
            model_name="horarioprescripcion",
            name="prescripcion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horarios",
                to="medicamentos.prescripcion",
            ),
        ),
        migrations.AddField(
            model_name="administracion",
            name="prescripcion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="administraciones",
                to="medicamentos.prescripcion",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingresomedicamento",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("hogar__isnull", True), ("residente__isnull", False)),
                    models.Q(("hogar__isnull", False), ("residente__isnull", True)),
                    _connector="OR",
                ),
                name="ingreso_dueno_unico_residente_o_hogar",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="horarioprescripcion",
            unique_together={("prescripcion", "hora")},
        ),
        migrations.AddConstraint(
            model_name="administracion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("anulada", False)),
                fields=("prescripcion", "fecha_programada"),
                name="uniq_administracion_prescripcion_fecha_programada",
            ),
        ),
    ]
