# Generated by Django 6.0.4 on 2026-10-01 04:06

import gammelcare.archivos_privados
import medicamentos.models
from django.db import migrations, models


def mover_formulas_al_almacenamiento_privado(apps, schema_editor):
    """Las fotos de fórmulas subidas antes de este cambio quedaron en el
    almacenamiento público por defecto (MEDIA_ROOT, que no estaba definido,
    es decir, la carpeta desde donde corría el servidor). Se mueven a
    PRIVATE_MEDIA_ROOT conservando el mismo nombre relativo, para que la
    referencia guardada en la base de datos siga siendo válida."""
    import os
    import shutil
    from django.conf import settings

    Prescripcion = apps.get_model('medicamentos', 'Prescripcion')
    destino_base = os.path.abspath(str(settings.PRIVATE_MEDIA_ROOT))
    origenes = {os.path.abspath(str(getattr(settings, 'MEDIA_ROOT', '') or settings.BASE_DIR)),
                os.path.abspath(str(settings.BASE_DIR)), os.path.abspath(os.getcwd())}
    for p in Prescripcion.objects.exclude(archivo_formula='').exclude(archivo_formula__isnull=True):
        nombre = p.archivo_formula.name
        destino = os.path.join(destino_base, nombre)
        if os.path.exists(destino):
            continue
        for base in origenes:
            origen = os.path.join(base, nombre)
            if os.path.isfile(origen):
                os.makedirs(os.path.dirname(destino), exist_ok=True)
                shutil.move(origen, destino)
                break


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administracion",
            name="cantidad_administrada",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Cantidad suministrada",
            ),
        ),
        migrations.AlterField(
            model_name="administracion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("administrado", "Suministrado"),
                    ("no_administrado", "No suministrado"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("entrada", "Entrada"),
                    ("salida_administracion", "Salida por suministro"),
                    ("ajuste", "Ajuste"),
                    ("descarte_vencido", "Descarte por vencimiento"),
                    ("devolucion_familia", "Devolución a la familia"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="prescripcion",
            name="archivo_formula",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=gammelcare.archivos_privados.AlmacenamientoPrivado(),
                upload_to=medicamentos.models._ruta_formula,
                verbose_name="Archivo de la fórmula (foto o escaneo)",
            ),
        ),
        migrations.RunPython(mover_formulas_al_almacenamiento_privado, migrations.RunPython.noop),
    ]
