# Generated by Django 6.0.4 on 2026-04-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoCIE10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('categoria', models.CharField(blank=True, max_length=200, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Código CIE-10',
                'verbose_name_plural': 'Códigos CIE-10',
                'db_table': 'catalogos_cie10',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'EPS',
                'verbose_name_plural': 'EPS',
                'db_table': 'catalogos_eps',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioAmbulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio de Ambulancia',
                'verbose_name_plural': 'Servicios de Ambulancia',
                'db_table': 'catalogos_servicio_ambulancia',
                'ordering': ['nombre'],
            },
        ),
    ]
