# Generated by Django 6.0.4 on 2026-10-02 00:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residentes", "0003_remove_expedienteingreso_diagnosticos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanAtencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("vigente", "Vigente"),
                            ("reemplazado", "Reemplazado"),
                        ],
                        default="borrador",
                        max_length=12,
                    ),
                ),
                (
                    "resumen",
                    models.TextField(
                        blank=True,
                        help_text="Resumen de la valoración integral que justifica el plan.",
                        verbose_name="Situación actual del residente",
                    ),
                ),
                (
                    "participantes",
                    models.TextField(
                        blank=True,
                        help_text="Profesionales, el residente y su familia.",
                        verbose_name="Quiénes participaron",
                    ),
                ),
                (
                    "acuerdos_familia",
                    models.TextField(
                        blank=True,
                        verbose_name="Acuerdos con el residente y la familia",
                    ),
                ),
                ("fecha_revision", models.DateField(verbose_name="Próxima revisión")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("fecha_activacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_reemplazo", models.DateTimeField(blank=True, null=True)),
                (
                    "activado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "anterior",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="siguiente",
                        to="plan_atencion.planatencion",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planes_atencion",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de atención",
                "verbose_name_plural": "Planes de atención",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="ObjetivoPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("funcional", "Funcionalidad y autocuidado"),
                            ("caidas", "Movilidad y prevención de caídas"),
                            ("cognitivo", "Cognición y orientación"),
                            ("afectivo", "Estado de ánimo y salud emocional"),
                            ("nutricion", "Nutrición e hidratación"),
                            ("piel", "Piel y prevención de lesiones por presión"),
                            ("eliminacion", "Eliminación (orina y deposición)"),
                            ("medicacion", "Medicamentos y condiciones crónicas"),
                            ("dolor", "Dolor y confort"),
                            ("social", "Familia y red de apoyo"),
                            ("actividades", "Actividades, ocio y participación"),
                            ("otro", "Otra"),
                        ],
                        max_length=15,
                        verbose_name="Área",
                    ),
                ),
                (
                    "necesidad",
                    models.TextField(
                        help_text="Qué se encontró en la valoración.",
                        verbose_name="Necesidad o problema",
                    ),
                ),
                (
                    "meta",
                    models.TextField(
                        help_text="Qué se quiere lograr, de forma que se pueda verificar.",
                        verbose_name="Objetivo",
                    ),
                ),
                (
                    "intervenciones",
                    models.TextField(
                        help_text="Qué se va a hacer, cómo y cada cuánto.",
                        verbose_name="Intervenciones",
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        choices=[
                            ("administrador", "Administrador del Hogar"),
                            ("medico", "Médico"),
                            ("enfermero", "Auxiliar de Enfermería"),
                            ("jefe_enfermeria", "Jefe de Enfermería"),
                            ("fisioterapeuta", "Fisioterapeuta"),
                            ("nutricionista", "Nutricionista"),
                            ("psicologo", "Psicólogo/a"),
                            ("trabajo_social", "Trabajador/a Social"),
                            ("terapeuta_ocupacional", "Terapeuta Ocupacional"),
                        ],
                        max_length=30,
                        verbose_name="Rol responsable",
                    ),
                ),
                (
                    "frecuencia",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Frecuencia"
                    ),
                ),
                ("fecha_meta", models.DateField(verbose_name="Fecha para evaluarlo")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_curso", "En curso"),
                            ("logrado", "Logrado"),
                            ("parcial", "Parcialmente logrado"),
                            ("no_logrado", "No logrado"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="en_curso",
                        max_length=12,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        blank=True,
                        help_text="Escala o hallazgo que lo sugirió.",
                        max_length=60,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "copiado_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="plan_atencion.objetivoplan",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objetivos",
                        to="plan_atencion.planatencion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objetivo del plan",
                "verbose_name_plural": "Objetivos del plan",
                "ordering": ["area", "fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="SeguimientoObjetivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_curso", "En curso"),
                            ("logrado", "Logrado"),
                            ("parcial", "Parcialmente logrado"),
                            ("no_logrado", "No logrado"),
                            ("suspendido", "Suspendido"),
                        ],
                        max_length=12,
                        verbose_name="Estado del objetivo",
                    ),
                ),
                ("nota", models.TextField(verbose_name="Qué se observó")),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "objetivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="plan_atencion.objetivoplan",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de objetivo",
                "verbose_name_plural": "Seguimientos de objetivos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddConstraint(
            model_name="planatencion",
            constraint=models.UniqueConstraint(
                fields=("residente", "version"), name="plan_version_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="planatencion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "vigente")),
                fields=("residente",),
                name="plan_vigente_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="planatencion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "borrador")),
                fields=("residente",),
                name="plan_borrador_unico",
            ),
        ),
    ]
