# Generated by Django 6.0.4 on 2026-10-01 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hogares", "0001_initial"),
        ("residentes", "0003_remove_expedienteingreso_diagnosticos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionValoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodicidad", models.JSONField(blank=True, default=dict)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hogar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_valoracion",
                        to="hogares.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de valoración geriátrica",
                "verbose_name_plural": "Configuraciones de valoración geriátrica",
            },
        ),
        migrations.CreateModel(
            name="Valoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "escala",
                    models.CharField(
                        choices=[
                            ("barthel", "Índice de Barthel"),
                            ("lawton", "Escala de Lawton y Brody"),
                            ("pfeiffer", "Cuestionario de Pfeiffer (SPMSQ)"),
                            ("mmse", "Minimental (MMSE)"),
                            (
                                "yesavage",
                                "Escala de depresión geriátrica de Yesavage (GDS-15)",
                            ),
                            ("tinetti", "Escala de Tinetti (equilibrio y marcha)"),
                            ("norton", "Escala de Norton"),
                            ("braden", "Escala de Braden"),
                            (
                                "mna_sf",
                                "Mini Nutritional Assessment, forma corta (MNA-SF)",
                            ),
                            ("zarit", "Escala de sobrecarga del cuidador de Zarit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Fecha de aplicación",
                    ),
                ),
                ("respuestas", models.JSONField(blank=True, default=dict)),
                ("educacion", models.CharField(blank=True, max_length=10)),
                ("puntaje", models.SmallIntegerField()),
                ("interpretacion", models.CharField(max_length=120)),
                ("nivel", models.CharField(max_length=10)),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "cuidador_evaluado",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Cuidador evaluado"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "hash_integridad",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("anulada", models.BooleanField(default=False)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "anulada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valoraciones",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valoración",
                "verbose_name_plural": "Valoraciones",
                "ordering": ["-fecha", "-fecha_registro"],
                "indexes": [
                    models.Index(
                        fields=["residente", "escala", "fecha"],
                        name="valoracion__residen_5b2212_idx",
                    )
                ],
            },
        ),
    ]
