# Generated by Django 6.0.4 on 2026-10-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valoracion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="valoracion",
            name="cuidador_evaluado",
        ),
        migrations.AlterField(
            model_name="valoracion",
            name="escala",
            field=models.CharField(
                choices=[
                    ("katz", "Índice de Katz"),
                    ("lawton", "Escala de Lawton y Brody"),
                    ("pfeiffer", "Cuestionario de Pfeiffer (SPMSQ)"),
                    ("yesavage", "Escala de depresión geriátrica de Yesavage (GDS-15)"),
                    ("tinetti", "Escala de Tinetti (equilibrio y marcha)"),
                    ("norton", "Escala de Norton"),
                ],
                max_length=20,
            ),
        ),
    ]
