# Generated by Django 6.0.4 on 2026-10-01 23:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hogares", "0001_initial"),
        ("residentes", "0003_remove_expedienteingreso_diagnosticos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RangosHogar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rangos", models.JSONField(blank=True, default=dict)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hogar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rangos_signos",
                        to="hogares.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rangos de signos vitales del hogar",
                "verbose_name_plural": "Rangos de signos vitales de los hogares",
            },
        ),
        migrations.CreateModel(
            name="ControlSignos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha y hora de la toma",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "hash_integridad",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("anulado", models.BooleanField(default=False)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "pas",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Presión sistólica (mmHg)"
                    ),
                ),
                (
                    "pad",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Presión diastólica (mmHg)"
                    ),
                ),
                (
                    "fc",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Frecuencia cardiaca (lpm)"
                    ),
                ),
                (
                    "fr",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Frecuencia respiratoria (rpm)",
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Temperatura (°C)",
                    ),
                ),
                (
                    "spo2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Saturación de oxígeno (%)"
                    ),
                ),
                (
                    "oxigeno_suplementario",
                    models.BooleanField(
                        default=False, verbose_name="Con oxígeno suplementario"
                    ),
                ),
                (
                    "litros_oxigeno",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Litros por minuto",
                    ),
                ),
                (
                    "glucometria",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Glucometría (mg/dL)"
                    ),
                ),
                (
                    "momento_glucometria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ayunas", "En ayunas"),
                            ("preprandial", "Antes de comer"),
                            ("postprandial", "Dos horas después de comer"),
                            ("aleatoria", "En otro momento"),
                        ],
                        max_length=15,
                        verbose_name="Momento de la glucometría",
                    ),
                ),
                (
                    "dolor",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Dolor (0 a 10)"
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controles_signos",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control de signos vitales",
                "verbose_name_plural": "Controles de signos vitales",
                "ordering": ["-fecha_hora"],
                "indexes": [
                    models.Index(
                        fields=["residente", "fecha_hora"],
                        name="signos_cont_residen_e99502_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RangoResidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parametro",
                    models.CharField(
                        choices=[
                            ("pas", "Presión arterial sistólica"),
                            ("pad", "Presión arterial diastólica"),
                            ("fc", "Frecuencia cardiaca"),
                            ("fr", "Frecuencia respiratoria"),
                            ("temperatura", "Temperatura"),
                            ("spo2", "Saturación de oxígeno"),
                            ("glucometria", "Glucometría"),
                            ("dolor", "Dolor (escala 0 a 10)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "critico_min",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "normal_min",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "normal_max",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "critico_max",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("motivo", models.TextField()),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_inactivacion", models.DateTimeField(blank=True, null=True)),
                (
                    "definido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inactivado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rangos_signos",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rango de signos vitales del residente",
                "verbose_name_plural": "Rangos de signos vitales de residentes",
                "ordering": ["parametro", "-fecha"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("activo", True)),
                        fields=("residente", "parametro"),
                        name="rango_residente_activo_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroLiquidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha y hora de la toma",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "hash_integridad",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("anulado", models.BooleanField(default=False)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ingreso", "Ingreso (lo que recibió)"),
                            ("egreso", "Egreso (lo que eliminó)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "via",
                    models.CharField(
                        choices=[
                            ("oral", "Ingreso — vía oral"),
                            ("sonda", "Ingreso — sonda o gastrostomía"),
                            ("intravenosa", "Ingreso — líquidos intravenosos"),
                            ("subcutanea", "Ingreso — hipodermoclisis"),
                            ("otro_ingreso", "Ingreso — otro"),
                            ("orina", "Egreso — orina"),
                            ("vomito", "Egreso — vómito"),
                            ("deposicion_liquida", "Egreso — deposición líquida"),
                            ("drenaje", "Egreso — drenaje o sonda"),
                            ("otro_egreso", "Egreso — otro"),
                        ],
                        max_length=20,
                        verbose_name="Vía o tipo",
                    ),
                ),
                (
                    "cantidad_ml",
                    models.PositiveIntegerField(verbose_name="Cantidad (mL)"),
                ),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_liquidos",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de líquidos",
                "verbose_name_plural": "Registros de líquidos",
                "ordering": ["-fecha_hora"],
                "indexes": [
                    models.Index(
                        fields=["residente", "fecha_hora"],
                        name="signos_regi_residen_32ef10_idx",
                    )
                ],
            },
        ),
    ]
