# Generated by Django 6.0.4 on 2026-10-01 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogos", "0001_initial"),
        ("medicamentos", "0002_nombres_y_formula_privada"),
        ("residentes", "0003_remove_expedienteingreso_diagnosticos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alergia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("motivo_inactivacion", models.TextField(blank=True)),
                ("fecha_inactivacion", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("medicamento", "Medicamento"),
                            ("alimento", "Alimento"),
                            ("ambiental", "Ambiental (polen, ácaros, látex…)"),
                            ("otra", "Otra"),
                        ],
                        default="medicamento",
                        max_length=20,
                    ),
                ),
                (
                    "sustancia",
                    models.CharField(
                        help_text='A qué es alérgico, como lo diría el personal: "Penicilina", "Mariscos", "Látex".',
                        max_length=150,
                    ),
                ),
                (
                    "reaccion",
                    models.CharField(
                        choices=[
                            ("erupcion", "Erupción o urticaria"),
                            ("angioedema", "Hinchazón de cara, labios o lengua"),
                            ("respiratoria", "Dificultad para respirar"),
                            ("anafilaxia", "Anafilaxia"),
                            ("gastrointestinal", "Náuseas, vómito o diarrea"),
                            ("otra", "Otra"),
                            ("desconocida", "No se sabe"),
                        ],
                        default="desconocida",
                        max_length=20,
                        verbose_name="Reacción",
                    ),
                ),
                (
                    "descripcion_reaccion",
                    models.TextField(blank=True, verbose_name="Detalle de la reacción"),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("grave", "Grave"),
                            ("moderada", "Moderada"),
                            ("leve", "Leve"),
                            ("desconocida", "No se sabe"),
                        ],
                        default="desconocida",
                        max_length=20,
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        choices=[
                            ("familia", "Lo informó la familia o el acudiente"),
                            ("historia", "Historia clínica o epicrisis previa"),
                            ("residente", "Lo informó el residente"),
                            ("observada", "Reacción observada en el hogar"),
                        ],
                        default="familia",
                        max_length=20,
                        verbose_name="¿Quién lo informó?",
                    ),
                ),
                (
                    "inactivado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si es alérgico a un medicamento del catálogo, elíjalo: el sistema avisará al formularlo.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alergias",
                        to="medicamentos.medicamento",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alergias",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alergia",
                "verbose_name_plural": "Alergias",
                "db_table": "antecedentes_alergias",
                "ordering": ["-activo", "tipo", "sustancia"],
            },
        ),
        migrations.CreateModel(
            name="Antecedente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("motivo_inactivacion", models.TextField(blank=True)),
                ("fecha_inactivacion", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("patologico", "Enfermedad (patológico)"),
                            ("quirurgico", "Cirugía (quirúrgico)"),
                            ("traumatico", "Fractura o trauma"),
                            ("toxico", "Tabaco, alcohol u otras sustancias"),
                            ("familiar", "Enfermedad en la familia"),
                            ("otro", "Otro"),
                        ],
                        default="patologico",
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "cuando",
                    models.CharField(
                        blank=True,
                        help_text='Como se sepa: "2015", "hace 10 años", "en la infancia".',
                        max_length=60,
                        verbose_name="¿Cuándo?",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "codigo_cie10",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogos.codigocie10",
                        verbose_name="Código CIE-10 (opcional)",
                    ),
                ),
                (
                    "inactivado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="antecedentes",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antecedente",
                "verbose_name_plural": "Antecedentes",
                "db_table": "antecedentes_antecedentes",
                "ordering": ["-activo", "tipo", "-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="EstadoAlergias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sin_alergias_conocidas", models.BooleanField(default=False)),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estado_alergias",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de alergias",
                "verbose_name_plural": "Estados de alergias",
                "db_table": "antecedentes_estado_alergias",
            },
        ),
    ]
