# Generated by Django 6.0.4 on 2026-10-01 04:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hogares", "0001_initial"),
        ("residentes", "0003_remove_expedienteingreso_diagnosticos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regla", models.CharField(max_length=40)),
                ("clave", models.CharField(max_length=120)),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("sistema", "Sistema"),
                            ("manual", "Aviso del personal"),
                        ],
                        default="sistema",
                        max_length=10,
                    ),
                ),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("critica", "Crítica"),
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("informativa", "Informativa"),
                        ],
                        max_length=12,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField(blank=True)),
                ("url_accion", models.CharField(blank=True, max_length=300)),
                ("texto_accion", models.CharField(blank=True, max_length=60)),
                ("roles_destino", models.CharField(max_length=300)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("nueva", "Nueva"),
                            ("atendida", "Atendida"),
                            ("resuelta", "Resuelta por el sistema"),
                            ("descartada", "Descartada"),
                            ("vencida", "Vencida"),
                        ],
                        default="nueva",
                        max_length=12,
                    ),
                ),
                ("vigente", models.BooleanField(default=True)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("vence", models.DateTimeField(blank=True, null=True)),
                ("fecha_atencion", models.DateTimeField(blank=True, null=True)),
                ("nota_atencion", models.TextField(blank=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "atendida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="hogares.hogar",
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alertas",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionAlertas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("umbrales", models.JSONField(blank=True, default=dict)),
                ("reglas_desactivadas", models.JSONField(blank=True, default=list)),
                ("ultima_evaluacion", models.DateTimeField(blank=True, null=True)),
                (
                    "hogar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_alertas",
                        to="hogares.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de alertas",
                "verbose_name_plural": "Configuraciones de alertas",
            },
        ),
        migrations.CreateModel(
            name="VistaAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "alerta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vistas",
                        to="alertas.alerta",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(
                fields=["hogar", "estado"], name="alertas_ale_hogar_i_bc052d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="alerta",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vigente", True)),
                fields=("hogar", "clave"),
                name="alerta_vigente_unica_por_clave",
            ),
        ),
        migrations.AddConstraint(
            model_name="vistaalerta",
            constraint=models.UniqueConstraint(
                fields=("alerta", "usuario"), name="vista_alerta_unica"
            ),
        ),
    ]
