# Generated by Django 6.0.4 on 2026-10-03 05:02

import cuidados.models
import django.db.models.deletion
import django.utils.timezone
import gammelcare.archivos_privados
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residentes", "0003_remove_expedienteingreso_diagnosticos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Herida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("lpp", "Lesión por presión"),
                            ("humedad", "Lesión por humedad (dermatitis del pañal)"),
                            ("desgarro", "Desgarro cutáneo"),
                            ("traumatica", "Herida por caída o golpe"),
                            ("quirurgica", "Herida quirúrgica"),
                            ("venosa", "Úlcera venosa"),
                            ("arterial", "Úlcera arterial"),
                            ("pie_diabetico", "Pie diabético"),
                            ("quemadura", "Quemadura"),
                            ("otra", "Otra"),
                        ],
                        default="lpp",
                        max_length=15,
                        verbose_name="Tipo de herida",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        choices=[
                            ("sacro", "Sacro"),
                            ("coxis", "Coxis"),
                            ("gluteo_der", "Glúteo derecho"),
                            ("gluteo_izq", "Glúteo izquierdo"),
                            ("isquion_der", "Isquion derecho"),
                            ("isquion_izq", "Isquion izquierdo"),
                            ("trocanter_der", "Cadera derecha (trocánter)"),
                            ("trocanter_izq", "Cadera izquierda (trocánter)"),
                            ("talon_der", "Talón derecho"),
                            ("talon_izq", "Talón izquierdo"),
                            ("maleolo_der", "Tobillo derecho (maléolo)"),
                            ("maleolo_izq", "Tobillo izquierdo (maléolo)"),
                            ("pie_der", "Pie derecho"),
                            ("pie_izq", "Pie izquierdo"),
                            ("pierna_der", "Pierna derecha"),
                            ("pierna_izq", "Pierna izquierda"),
                            ("rodilla_der", "Rodilla derecha"),
                            ("rodilla_izq", "Rodilla izquierda"),
                            ("codo_der", "Codo derecho"),
                            ("codo_izq", "Codo izquierdo"),
                            ("brazo_der", "Brazo o antebrazo derecho"),
                            ("brazo_izq", "Brazo o antebrazo izquierdo"),
                            ("mano_der", "Mano derecha"),
                            ("mano_izq", "Mano izquierda"),
                            ("escapula", "Espalda (omóplatos)"),
                            ("columna", "Columna"),
                            ("occipital", "Nuca (occipital)"),
                            ("oreja_der", "Oreja derecha"),
                            ("oreja_izq", "Oreja izquierda"),
                            ("cara", "Cara"),
                            ("abdomen", "Abdomen"),
                            ("otra", "Otra"),
                        ],
                        max_length=20,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "ubicacion_detalle",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Detalle de la ubicación",
                    ),
                ),
                (
                    "estadio_inicial",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "1",
                                "Estadio 1 — piel intacta, enrojecimiento que no blanquea",
                            ),
                            (
                                "2",
                                "Estadio 2 — pérdida parcial de la piel (ampolla o erosión)",
                            ),
                            ("3", "Estadio 3 — pérdida total de la piel, se ve grasa"),
                            ("4", "Estadio 4 — se ve músculo, tendón o hueso"),
                            (
                                "no_estadificable",
                                "No estadificable — cubierta por esfacelo o escara",
                            ),
                            (
                                "tejido_profundo",
                                "Lesión de tejido profundo — piel morada o granate",
                            ),
                        ],
                        max_length=20,
                        verbose_name="Estadio al detectarla",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("hogar", "Apareció en el hogar"),
                            ("ingreso", "Ya la traía al ingresar al hogar"),
                            ("hospital", "Llegó así de una hospitalización o salida"),
                        ],
                        default="hogar",
                        max_length=10,
                        verbose_name="¿Dónde apareció?",
                    ),
                ),
                (
                    "fecha_deteccion",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Fecha en que se detectó",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción inicial"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activa", "Activa"), ("cerrada", "Cerrada")],
                        default="activa",
                        max_length=10,
                    ),
                ),
                (
                    "motivo_cierre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cicatrizada", "Cicatrizó"),
                            ("egreso", "El residente egresó o fue trasladado"),
                            ("fallecimiento", "Fallecimiento"),
                            ("error", "Se registró por error"),
                        ],
                        max_length=15,
                    ),
                ),
                ("nota_cierre", models.TextField(blank=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "cerrada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="heridas",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Herida",
                "verbose_name_plural": "Heridas",
                "ordering": ["estado", "-fecha_deteccion"],
            },
        ),
        migrations.CreateModel(
            name="PlanCuidados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banio",
                    models.CharField(
                        choices=[
                            ("diario", "Todos los días"),
                            ("interdiario", "Día de por medio"),
                            ("no_aplica", "No se registra"),
                        ],
                        default="diario",
                        max_length=12,
                        verbose_name="Baño",
                    ),
                ),
                (
                    "usa_panal",
                    models.BooleanField(default=False, verbose_name="Usa pañal"),
                ),
                (
                    "cambios_posicion",
                    models.BooleanField(
                        default=False,
                        help_text="Para residentes en cama o con riesgo de lesiones por presión.",
                        verbose_name="Necesita cambios de posición",
                    ),
                ),
                (
                    "intervalo_posicion_horas",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2, "Cada 2 horas"),
                            (3, "Cada 3 horas"),
                            (4, "Cada 4 horas"),
                        ],
                        default=2,
                        verbose_name="Cada cuánto",
                    ),
                ),
                (
                    "higiene_oral",
                    models.BooleanField(default=True, verbose_name="Higiene oral"),
                ),
                (
                    "movilizacion",
                    models.BooleanField(
                        default=False,
                        verbose_name="Movilización (levantar, caminar o ejercicios)",
                    ),
                ),
                (
                    "indicaciones",
                    models.TextField(
                        blank=True,
                        help_text="Ej.: colchón antiescaras, protección de talones, baño con ayuda de dos personas.",
                        verbose_name="Indicaciones especiales",
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_cuidados",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de cuidados",
                "verbose_name_plural": "Planes de cuidados",
            },
        ),
        migrations.CreateModel(
            name="SeguimientoHerida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "hash_integridad",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("anulado", models.BooleanField(default=False)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "largo_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Largo (cm)",
                    ),
                ),
                (
                    "ancho_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Ancho (cm)",
                    ),
                ),
                (
                    "profundidad_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Profundidad (cm)",
                    ),
                ),
                (
                    "estadio",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "1",
                                "Estadio 1 — piel intacta, enrojecimiento que no blanquea",
                            ),
                            (
                                "2",
                                "Estadio 2 — pérdida parcial de la piel (ampolla o erosión)",
                            ),
                            ("3", "Estadio 3 — pérdida total de la piel, se ve grasa"),
                            ("4", "Estadio 4 — se ve músculo, tendón o hueso"),
                            (
                                "no_estadificable",
                                "No estadificable — cubierta por esfacelo o escara",
                            ),
                            (
                                "tejido_profundo",
                                "Lesión de tejido profundo — piel morada o granate",
                            ),
                        ],
                        max_length=20,
                        verbose_name="Estadio actual",
                    ),
                ),
                (
                    "lecho",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("epitelizacion", "Epitelización (piel nueva, rosada)"),
                            ("granulacion", "Granulación (rojo, húmedo, sano)"),
                            ("esfacelo", "Esfacelo (amarillo o blanco, adherido)"),
                            ("necrosis", "Necrosis o escara (negra o café, seca)"),
                            ("mixto", "Mixto"),
                        ],
                        max_length=15,
                        verbose_name="Aspecto del fondo de la herida",
                    ),
                ),
                (
                    "exudado",
                    models.CharField(
                        choices=[
                            ("ninguno", "Ninguno"),
                            ("escaso", "Escaso"),
                            ("moderado", "Moderado"),
                            ("abundante", "Abundante"),
                        ],
                        default="ninguno",
                        max_length=10,
                        verbose_name="Secreción",
                    ),
                ),
                (
                    "piel_alrededor",
                    models.CharField(
                        choices=[
                            ("sana", "Sana"),
                            ("enrojecida", "Enrojecida"),
                            ("macerada", "Macerada (blanca, húmeda)"),
                            ("edema", "Hinchada"),
                            ("seca", "Seca o descamada"),
                        ],
                        default="sana",
                        max_length=12,
                        verbose_name="Piel alrededor",
                    ),
                ),
                (
                    "signos_infeccion",
                    models.BooleanField(
                        default=False,
                        verbose_name="Signos de infección (calor, pus, mal olor, enrojecimiento que se extiende)",
                    ),
                ),
                (
                    "dolor",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Dolor (0 a 10)"
                    ),
                ),
                (
                    "curacion",
                    models.TextField(
                        blank=True,
                        help_text="Limpieza, producto y apósito usados.",
                        verbose_name="Curación realizada",
                    ),
                ),
                (
                    "proxima_curacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima curación"
                    ),
                ),
                (
                    "foto",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=gammelcare.archivos_privados.AlmacenamientoPrivado(),
                        upload_to=cuidados.models._ruta_foto,
                    ),
                ),
                ("foto_tipo", models.CharField(blank=True, max_length=50)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "herida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos",
                        to="cuidados.herida",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de herida",
                "verbose_name_plural": "Seguimientos de heridas",
                "ordering": ["-fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="RegistroCuidado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "hash_integridad",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("anulado", models.BooleanField(default=False)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("banio", "Baño"),
                            ("panal", "Cambio de pañal"),
                            ("posicion", "Cambio de posición"),
                            ("higiene_oral", "Higiene oral"),
                            ("movilizacion", "Movilización"),
                        ],
                        max_length=15,
                    ),
                ),
                ("detalle", models.CharField(max_length=20)),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Hora en que se hizo",
                    ),
                ),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuidados",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de cuidado",
                "verbose_name_plural": "Registros de cuidados",
                "ordering": ["-fecha_hora"],
                "indexes": [
                    models.Index(
                        fields=["residente", "tipo", "fecha_hora"],
                        name="cuidados_re_residen_e7e40f_idx",
                    )
                ],
            },
        ),
    ]
