# Generated by Django 6.0.4 on 2026-10-03 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hogares", "0001_initial"),
        ("residentes", "0003_remove_expedienteingreso_diagnosticos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionNutricion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comidas_activas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Códigos de las comidas que sirve el hogar. Vacío = todas.",
                    ),
                ),
                ("horas", models.JSONField(blank=True, default=dict)),
                (
                    "vaso_ml",
                    models.PositiveSmallIntegerField(
                        default=200, verbose_name="Tamaño del vaso (mL)"
                    ),
                ),
                (
                    "meta_liquidos_ml",
                    models.PositiveIntegerField(
                        default=1500,
                        verbose_name="Meta diaria de líquidos por defecto (mL)",
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hogar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_nutricion",
                        to="hogares.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de nutrición",
                "verbose_name_plural": "Configuraciones de nutrición",
            },
        ),
        migrations.CreateModel(
            name="TipoDieta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=100)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_dieta",
                        to="hogares.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de dieta",
                "verbose_name_plural": "Tipos de dieta",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="RegistroIngesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "comida",
                    models.CharField(
                        choices=[
                            ("desayuno", "Desayuno"),
                            ("media_manana", "Media mañana"),
                            ("almuerzo", "Almuerzo"),
                            ("onces", "Onces"),
                            ("cena", "Cena"),
                            ("nocturno", "Refrigerio nocturno"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "consumo",
                    models.CharField(
                        choices=[
                            ("todo", "Todo"),
                            ("tres_cuartos", "¾"),
                            ("mitad", "La mitad"),
                            ("cuarto", "¼"),
                            ("nada", "Nada"),
                            ("rechazo", "Lo rechazó"),
                            ("ausente", "No estaba (cita, salida, hospital o ayuno)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "hash_integridad",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("anulado", models.BooleanField(default=False)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestas",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de ingesta",
                "verbose_name_plural": "Registros de ingesta",
                "ordering": ["-fecha", "-fecha_registro"],
                "indexes": [
                    models.Index(
                        fields=["residente", "fecha"],
                        name="nutricion_r_residen_4d7461_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("anulado", False)),
                        fields=("residente", "fecha", "comida"),
                        name="ingesta_vigente_unica",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DietaResidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "textura",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("blanda", "Blanda o picada fina"),
                            ("molida", "Molida o en puré"),
                            ("licuada", "Licuada o líquida"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "liquidos",
                    models.CharField(
                        choices=[
                            ("normal", "Líquidos normales"),
                            ("nectar", "Espesados — néctar"),
                            ("miel", "Espesados — miel"),
                            ("pudin", "Espesados — pudín"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Consistencia de los líquidos",
                    ),
                ),
                (
                    "ayuda",
                    models.CharField(
                        choices=[
                            ("independiente", "Come solo"),
                            ("supervision", "Come solo con supervisión"),
                            ("parcial", "Necesita ayuda parcial"),
                            ("total", "Hay que darle de comer"),
                            ("sonda", "Alimentación por sonda"),
                        ],
                        default="independiente",
                        max_length=15,
                        verbose_name="Ayuda para comer",
                    ),
                ),
                (
                    "meta_liquidos_ml",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vacío = la meta general del hogar.",
                        null=True,
                        verbose_name="Meta de líquidos al día (mL)",
                    ),
                ),
                (
                    "restriccion_liquidos_ml",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Solo si el médico restringió los líquidos.",
                        null=True,
                        verbose_name="Máximo de líquidos al día (mL)",
                    ),
                ),
                (
                    "alimentos_evitar",
                    models.TextField(
                        blank=True, verbose_name="Alimentos que debe evitar"
                    ),
                ),
                (
                    "preferencias",
                    models.TextField(blank=True, verbose_name="Gustos y preferencias"),
                ),
                (
                    "indicaciones",
                    models.TextField(
                        blank=True,
                        help_text="Ej.: fraccionar en 6 comidas, sentarlo a 90°, suplemento en las onces.",
                        verbose_name="Otras indicaciones",
                    ),
                ),
                (
                    "indicada_por",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Quién la indicó"
                    ),
                ),
                ("vigente", models.BooleanField(default=True)),
                (
                    "fecha_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dietas",
                        to="residentes.residente",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="nutricion.tipodieta",
                        verbose_name="Tipo de dieta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dieta del residente",
                "verbose_name_plural": "Dietas de los residentes",
                "ordering": ["-fecha_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("vigente", True)),
                        fields=("residente",),
                        name="dieta_vigente_unica",
                    )
                ],
            },
        ),
    ]
