# Generated by Django 6.0.4 on 2026-05-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='usuarios.rol', verbose_name='Roles'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('superadmin', 'Superadministrador'), ('administrador', 'Administrador del Hogar'), ('medico', 'Médico'), ('enfermero', 'Enfermero/a'), ('fisioterapeuta', 'Fisioterapeuta'), ('nutricionista', 'Nutricionista'), ('psicologo', 'Psicólogo/a'), ('trabajo_social', 'Trabajador/a Social'), ('terapeuta_ocupacional', 'Terapeuta Ocupacional')], max_length=50, unique=True),
        ),
    ]
