# Generated by Django 5.2.17 on 2026-09-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_quitar_hogar_de_superadmins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rol",
            name="nombre",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadministrador"),
                    ("administrador", "Administrador del Hogar"),
                    ("medico", "Médico"),
                    ("enfermero", "Auxiliar de Enfermería"),
                    ("jefe_enfermeria", "Jefe de Enfermería"),
                    ("fisioterapeuta", "Fisioterapeuta"),
                    ("nutricionista", "Nutricionista"),
                    ("psicologo", "Psicólogo/a"),
                    ("trabajo_social", "Trabajador/a Social"),
                    ("terapeuta_ocupacional", "Terapeuta Ocupacional"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
