# Generated by Django 6.0.4 on 2026-10-01 02:31

import django.db.models.deletion
import django.utils.timezone
import examenes.models
import examenes.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residentes", "0003_remove_expedienteingreso_diagnosticos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalitoCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.SlugField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("unidad", models.CharField(max_length=30)),
                (
                    "ref_min",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "ref_max",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "critico_min",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "critico_max",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=255)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Analito",
                "verbose_name_plural": "Analitos",
                "db_table": "examenes_analitos",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("laboratorio", "Laboratorio clínico"),
                            ("imagen", "Imagen diagnóstica"),
                            ("electrocardiograma", "Electrocardiograma"),
                            ("otro", "Otro paraclínico"),
                        ],
                        default="laboratorio",
                        max_length=30,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text='Qué se ordenó, p. ej. "Hemograma, glucosa y creatinina" o "Rx de tórax".',
                        max_length=200,
                    ),
                ),
                (
                    "ordenado_por",
                    models.CharField(
                        blank=True,
                        help_text="Profesional que ordenó el examen (puede ser externo al hogar).",
                        max_length=150,
                    ),
                ),
                (
                    "entidad",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="EPS, IPS o laboratorio",
                    ),
                ),
                (
                    "fecha_orden",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de la orden"
                    ),
                ),
                (
                    "indicaciones",
                    models.TextField(
                        blank=True, help_text="Ayuno, preparación, motivo de la orden."
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de resultado"),
                            ("resultado", "Pendiente de revisión médica"),
                            ("revisado", "Revisado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_toma",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de toma o realización",
                    ),
                ),
                (
                    "conclusion",
                    models.TextField(
                        blank=True,
                        help_text="Para imágenes, electrocardiogramas y otros informes en texto.",
                        verbose_name="Conclusión del informe",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("fecha_resultado", models.DateTimeField(blank=True, null=True)),
                ("fecha_cancelacion", models.DateTimeField(blank=True, null=True)),
                ("motivo_cancelacion", models.TextField(blank=True)),
                (
                    "cancelado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="examenes_cancelados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="examenes_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="examenes",
                        to="residentes.residente",
                    ),
                ),
                (
                    "resultado_cargado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_cargados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen",
                "verbose_name_plural": "Exámenes",
                "db_table": "examenes",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="ArchivoResultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        max_length=255,
                        storage=examenes.storage.AlmacenamientoPrivado(),
                        upload_to=examenes.models._ruta_archivo,
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("tamano_bytes", models.PositiveIntegerField()),
                ("sha256", models.CharField(editable=False, max_length=64)),
                (
                    "motivo",
                    models.TextField(
                        blank=True,
                        help_text="Obligatorio si se agrega después del resultado inicial (información adicional).",
                    ),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archivos",
                        to="examenes.examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo de resultado",
                "verbose_name_plural": "Archivos de resultado",
                "db_table": "examenes_archivos",
                "ordering": ["fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="RevisionMedica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interpretacion",
                    models.TextField(
                        blank=True, verbose_name="Hallazgos e interpretación"
                    ),
                ),
                ("conducta", models.TextField(verbose_name="Conducta")),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("hash_integridad", models.CharField(editable=False, max_length=64)),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisiones",
                        to="examenes.examen",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisión médica",
                "verbose_name_plural": "Revisiones médicas",
                "db_table": "examenes_revisiones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ValorResultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("valor", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unidad", models.CharField(blank=True, max_length=30)),
                (
                    "ref_min",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "ref_max",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "critico_min",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "critico_max",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("motivo_correccion", models.TextField(blank=True)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("hash_integridad", models.CharField(editable=False, max_length=64)),
                (
                    "analito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valores",
                        to="examenes.analitocatalogo",
                    ),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valores",
                        to="examenes.examen",
                    ),
                ),
                (
                    "reemplaza",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corregido_por",
                        to="examenes.valorresultado",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de resultado",
                "verbose_name_plural": "Valores de resultado",
                "db_table": "examenes_valores",
                "ordering": ["analito__orden", "nombre", "fecha_registro"],
            },
        ),
        migrations.AddIndex(
            model_name="examen",
            index=models.Index(
                fields=["estado", "fecha_registro"], name="examenes_estado_8baaca_idx"
            ),
        ),
    ]
