# Generated by Django 6.0.4 on 2026-10-01 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examenes", "0003_analitos_por_hogar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analitocatalogo",
            options={
                "ordering": ["orden", "nombre"],
                "verbose_name": "Parámetro de laboratorio",
                "verbose_name_plural": "Parámetros de laboratorio",
            },
        ),
    ]
