# Generated by Django 6.0.4 on 2026-10-01 04:51

import citas.models
import django.db.models.deletion
import django.utils.timezone
import gammelcare.archivos_privados
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residentes", "0003_remove_expedienteingreso_diagnosticos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("control", "Control de medicina general"),
                            ("especialista", "Especialista"),
                            ("odontologia", "Odontología"),
                            ("toma_muestra", "Toma de muestras de laboratorio"),
                            ("imagen", "Imágenes diagnósticas"),
                            ("terapia", "Terapia"),
                            ("procedimiento", "Procedimiento"),
                            ("otro", "Otra"),
                        ],
                        default="control",
                        max_length=20,
                        verbose_name="Tipo de cita",
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Especialidad o servicio",
                    ),
                ),
                (
                    "profesional",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Profesional"
                    ),
                ),
                (
                    "lugar",
                    models.CharField(
                        max_length=200, verbose_name="Lugar (entidad y dirección)"
                    ),
                ),
                ("fecha_hora", models.DateTimeField(verbose_name="Fecha y hora")),
                (
                    "requiere_ayuno",
                    models.BooleanField(default=False, verbose_name="Requiere ayuno"),
                ),
                (
                    "preparacion",
                    models.TextField(
                        blank=True, verbose_name="Preparación e indicaciones"
                    ),
                ),
                (
                    "acompanante",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Quién lo acompaña"
                    ),
                ),
                (
                    "transporte",
                    models.CharField(
                        choices=[
                            ("por_definir", "Por definir"),
                            ("hogar", "Vehículo del hogar"),
                            ("familia", "La familia lo lleva"),
                            ("eps", "Transporte de la EPS"),
                            ("ambulancia", "Ambulancia"),
                            ("taxi", "Taxi o transporte público"),
                            ("en_el_hogar", "No sale: la atención es en el hogar"),
                        ],
                        default="por_definir",
                        max_length=20,
                        verbose_name="Transporte",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("cumplida", "Cumplida"),
                            ("no_asistio", "No asistió"),
                            ("cancelada", "Cancelada"),
                            ("reprogramada", "Reprogramada"),
                        ],
                        default="programada",
                        max_length=15,
                    ),
                ),
                (
                    "resumen",
                    models.TextField(blank=True, verbose_name="Qué pasó en la cita"),
                ),
                (
                    "archivo_soporte",
                    models.FileField(
                        blank=True,
                        storage=gammelcare.archivos_privados.AlmacenamientoPrivado(),
                        upload_to=citas.models._ruta_soporte,
                        verbose_name="Soporte (fórmula, orden o resumen)",
                    ),
                ),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "cerrada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reprogramada_desde",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reprogramada_en",
                        to="citas.cita",
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita médica",
                "verbose_name_plural": "Citas médicas",
                "ordering": ["fecha_hora"],
                "indexes": [
                    models.Index(
                        fields=["estado", "fecha_hora"],
                        name="citas_cita_estado_50acb3_idx",
                    )
                ],
            },
        ),
    ]
