# Generated by Django 6.0.4 on 2026-04-30 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hogares', '0001_initial'),
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.BinaryField()),
                ('numero_documento', models.BinaryField()),
                ('contacto_emergencia', models.BinaryField()),
                ('fecha_nacimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cama_actual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residente_actual', to='infraestructura.cama')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residentes', to='hogares.hogar')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'db_table': 'residentes',
            },
        ),
        migrations.CreateModel(
            name='AsignacionCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='infraestructura.cama')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='residentes.residente')),
            ],
            options={
                'verbose_name': 'Asignación de Cama',
                'verbose_name_plural': 'Asignaciones de Cama',
                'db_table': 'asignaciones_cama',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
