# Generated by Django 6.0.4 on 2026-04-30 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='eps',
            field=models.CharField(blank=True, max_length=150, verbose_name='EPS'),
        ),
        migrations.AddField(
            model_name='residente',
            name='motivo_retiro',
            field=models.CharField(blank=True, choices=[('obito', 'Óbito'), ('fuga', 'Fuga'), ('retiro_voluntario', 'Retiro Voluntario'), ('traslado', 'Traslado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='nacionalidad',
            field=models.CharField(default='Colombiana', max_length=100),
        ),
        migrations.AddField(
            model_name='residente',
            name='servicio_ambulancia',
            field=models.CharField(blank=True, max_length=150, verbose_name='Servicio de Ambulancia'),
        ),
        migrations.AddField(
            model_name='residente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('NIT', 'NIT')], default='CC', max_length=10),
        ),
        migrations.CreateModel(
            name='ExpedienteIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosticos', models.TextField(blank=True, verbose_name='Diagnósticos')),
                ('examen_ingreso', models.TextField(blank=True, verbose_name='Examen de Ingreso')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('inventario_ingreso', models.TextField(blank=True, help_text='Lista de pertenencias del residente al momento del ingreso', verbose_name='Inventario de Ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('residente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='residentes.residente')),
            ],
            options={
                'verbose_name': 'Expediente de Ingreso',
                'verbose_name_plural': 'Expedientes de Ingreso',
                'db_table': 'expedientes_ingreso',
            },
        ),
    ]
