# Generated by Django 6.0.4 on 2026-04-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('residentes', '0002_residente_eps_residente_motivo_retiro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedienteingreso',
            name='diagnosticos',
        ),
        migrations.RemoveField(
            model_name='expedienteingreso',
            name='examen_ingreso',
        ),
        migrations.AlterField(
            model_name='expedienteingreso',
            name='inventario_ingreso',
            field=models.TextField(blank=True, verbose_name='Inventario de Ingreso'),
        ),
        migrations.AlterField(
            model_name='expedienteingreso',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones generales'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.eps', verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='servicio_ambulancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.servicioambulancia', verbose_name='Servicio de Ambulancia'),
        ),
        migrations.CreateModel(
            name='DiagnosticoResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo_cie10', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.codigocie10', verbose_name='Código CIE-10')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='residentes.residente')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'db_table': 'diagnosticos_residente',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ExamenIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla (cm)')),
                ('presion_arterial', models.CharField(blank=True, max_length=20, verbose_name='Presión arterial (mmHg)')),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca (lpm)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Saturación O2 (%)')),
                ('procedencia', models.CharField(blank=True, choices=[('hogar', 'Hogar familiar'), ('hospital', 'Hospital'), ('clinica', 'Clínica'), ('otro_hogar', 'Otro hogar geriátrico'), ('otro', 'Otro')], max_length=20)),
                ('estado_mental', models.CharField(blank=True, choices=[('orientado', 'Orientado'), ('desorientado_parcial', 'Desorientado parcialmente'), ('desorientado_total', 'Desorientado totalmente'), ('sedado', 'Sedado'), ('inconsciente', 'Inconsciente')], max_length=30, verbose_name='Estado mental')),
                ('movilidad', models.CharField(blank=True, choices=[('independiente', 'Independiente'), ('ayuda_parcial', 'Con ayuda parcial'), ('dependiente', 'Dependiente total'), ('en_cama', 'Postrado en cama')], max_length=20)),
                ('condicion_nutricional', models.CharField(blank=True, choices=[('normal', 'Normal'), ('desnutricion_leve', 'Desnutrición leve'), ('desnutricion_moderada', 'Desnutrición moderada'), ('desnutricion_severa', 'Desnutrición severa'), ('sobrepeso', 'Sobrepeso'), ('obesidad', 'Obesidad')], max_length=30, verbose_name='Condición nutricional')),
                ('observaciones_fisicas', models.TextField(blank=True, help_text='Golpes, cortes, heridas, amputaciones u otras condiciones físicas observadas', verbose_name='Observaciones físicas')),
                ('antecedentes_medicos', models.TextField(blank=True, verbose_name='Antecedentes médicos')),
                ('antecedentes_familiares', models.TextField(blank=True, verbose_name='Antecedentes familiares')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('residente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_ingreso', to='residentes.residente')),
            ],
            options={
                'verbose_name': 'Examen de Ingreso',
                'verbose_name_plural': 'Exámenes de Ingreso',
                'db_table': 'examenes_ingreso',
            },
        ),
    ]
