# Generated by Django 6.0.4 on 2026-10-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("residentes", "0003_remove_expedienteingreso_diagnosticos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exameningreso",
            name="antecedentes_familiares",
        ),
        migrations.RemoveField(
            model_name="exameningreso",
            name="antecedentes_medicos",
        ),
        migrations.RemoveField(
            model_name="expedienteingreso",
            name="alergias",
        ),
    ]
