# Generated by Django 6.0.4 on 2026-04-30 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('enfermeria', 'Nota de Enfermería'), ('evolucion', 'Evolución Médica')], max_length=20)),
                ('contenido', models.TextField()),
                ('hash_integridad', models.CharField(editable=False, max_length=64)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_creadas', to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='residentes.residente')),
            ],
            options={
                'verbose_name': 'Nota Clínica',
                'verbose_name_plural': 'Notas Clínicas',
                'db_table': 'notas_clinicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotaAclaratoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aclaraciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('nota_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aclaraciones', to='notas_clinicas.notaclinica')),
            ],
            options={
                'verbose_name': 'Nota Aclaratoria',
                'verbose_name_plural': 'Notas Aclaratorias',
                'db_table': 'notas_aclaratorias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
