# Generated by Django 6.0.4 on 2026-04-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaclinica',
            name='deposicion',
            field=models.BooleanField(default=False, verbose_name='Deposición positiva'),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='diuresis',
            field=models.BooleanField(default=False, verbose_name='Diuresis positiva'),
        ),
        migrations.AlterField(
            model_name='notaclinica',
            name='tipo',
            field=models.CharField(choices=[('enfermeria', 'Nota de Enfermería'), ('evolucion', 'Evolución Médica'), ('fisioterapia', 'Nota de Fisioterapia'), ('nutricion', 'Nota de Nutrición'), ('psicologia', 'Nota de Psicología'), ('trabajo_social', 'Nota de Trabajo Social'), ('terapia_ocupacional', 'Nota de Terapia Ocupacional')], max_length=30),
        ),
    ]
